version: '3.8'

name: dokku

services:
  dokku:
    image: dokku/dokku:0.30.2
    container_name: dokku
    ports:
      - 9022:22
    volumes:
      - dokku:/mnt/dokku
      - dokku-lib:/var/lib/dokku/ 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOKKU_HOSTNAME: dokku.me
      DOKKU_HOST_ROOT: /var/lib/dokku/home/dokku 
      DOKKU_LIB_HOST_ROOT: /var/lib/dokku

volumes:
  dokku-lib:
  dokku:
    name: "dokku"